[project]
name = "oracc2cdli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.1",
    "rapidfuzz>=3.14.3",
]
